server:
  port: 9000
swagger:
  host: localhost:9000

spring:
  datasource:
    driver-class-name: org.h2.Driver  # Database를 H2로 사용하겠다.
    url: jdbc:h2:~/test  # H2 접속 정보
    username: sa  # H2 접속 시 입력할 username 정보 (원하는 것으로 입력)
    password:  # H2 접속 시 입력할 password 정보 (원하는 것으로 입력)

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
        show_sql: false
        format_sql: true
    show-sql: false
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379