-- Typing Data

INSERT INTO TYPING (CREATED_DATE, UPDATED_DATE, CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'hahaha', true, 'English', 11, 0);

INSERT INTO TYPING (CREATED_DATE, UPDATED_DATE, CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Hello world', true, 'English', 11, 0);

INSERT INTO TYPING (CREATED_DATE, UPDATED_DATE, CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '소 잃고 외양간 고치기', true, 'Korean', 12, 0);

INSERT INTO TYPING (CREATED_DATE, UPDATED_DATE, CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'こんにちは世界', true, 'Japanese', 7, 0);