INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Curses like chickens come home to roost.', false, 'english', 40, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Custom is a second nature.', false, 'english', 26, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Everybody\u2019s business is nobody\u2019s business.', false, 'english', 42, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Everything comes to him who waits.', false, 'english', 34, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('All are not saints that go to church.', false, 'english', 37, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('All asses wag their ears.', false, 'english', 25, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Give a fool rope enough, and he will hang himself.', false, 'english', 50, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Curiosity killed a cat.', false, 'english', 23, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He is lifeless that is faultless.', false, 'english', 33, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He is not fit to command others that cannot command himself.', false, 'english', 60, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He is not laughed at that laughs at himself first.', false, 'english', 50, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He is not poor that has little, but he that desires much.', false, 'english', 57, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Many a true word is spoken in jest.', false, 'english', 35, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Many hands make light work.', false, 'english', 27, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Many men, many minds.', false, 'english', 21, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Last, but not least.', false, 'english', 20, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Laws catch flies, but let hornets go free.', false, 'english', 42, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Learn to creep before you leap.', false, 'english', 31, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Oaks may fall when reeds stand the storm.', false, 'english', 41, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Of two evils choose the least.', false, 'english', 30, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Old birds are not caught with chaff.', false, 'english', 36, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Old friends and old wine are best.', false, 'english', 34, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Out of sight, out of mind.', false, 'english', 26, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Out of the frying-pan into the fire.', false, 'english', 36, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Packed like herrings.', false, 'english', 21, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Learn to say before you sing.', false, 'english', 29, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Least said, soonest mended.', false, 'english', 27, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Leaves without figs.', false, 'english', 20, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Let bygones be bygones.', false, 'english', 23, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Many words hurt more than swords.', false, 'english', 33, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Many words will not fill a bushel.', false, 'english', 34, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Self done is soon done.', false, 'english', 23, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('The best fish smell when they are three days old.', false, 'english', 49, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('The best fish swim near the bottom.', false, 'english', 35, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('The best is oftentimes the enemy of the good.', false, 'english', 45, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Pleasure has a sting in its tail.', false, 'english', 33, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Plenty is no plague.', false, 'english', 20, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Politeness costs little (nothing), but yields much.', false, 'english', 51, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Poverty is no sin.', false, 'english', 18, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('They are hand and glove.', false, 'english', 24, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('They must hunger in winter that will not work in summer.', false, 'english', 56, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Things past cannot be recalled.', false, 'english', 31, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Think today and speak tomorrow.', false, 'english', 31, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('The busiest man finds the most leisure.', false, 'english', 39, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('The camel going to seek horns lost his ears.', false, 'english', 44, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('There is no fire without smoke.', false, 'english', 31, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('There is no place like home.', false, 'english', 28, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('There is no rose without a thorn.', false, 'english', 33, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('There is no rule without an exception.', false, 'english', 38, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('There is no smoke without fire.', false, 'english', 31, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Idleness is the mother of all evil.', false, 'english', 35, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Idleness rusts the mind.', false, 'english', 24, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('If an hole (donkey) bray at you, don\u2019t bray at him.', false, 'english', 51, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('If ifs and ans were pots and pans\u2026', false, 'english', 34, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('If my aunt had been a man, she\u2019d have been my uncle.', false, 'english', 52, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('If the blind lead the blind, both shall fall into the ditch..', false, 'english', 61, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('If the sky falls, we shall catch larks.', false, 'english', 39, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Men may meet but mountains never.', false, 'english', 33, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Mend or end (end or mend).', false, 'english', 26, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Might goes before right.', false, 'english', 24, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Misfortunes never come alone (singly).', false, 'english', 38, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Misfortunes tell us what fortune is.', false, 'english', 36, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('After rain comes fair weather.', false, 'english', 30, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('After us the deluge.', false, 'english', 20, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Agnes come on horseback, but go away on foot.', false, 'english', 45, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('All are good lasses, but whence come the bad wives?', false, 'english', 51, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('All are not friends that speak us fair.', false, 'english', 39, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('All are not hunters that blow the horn.', false, 'english', 39, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('All are not merry that dance lightly.', false, 'english', 37, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Custom is the plague of wise men and the idol of fools.', false, 'english', 55, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Cut your coat according to your cloth.', false, 'english', 38, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Death is the grand leveler.', false, 'english', 27, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Death pays all debts.', false, 'english', 21, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Death when it comes will have no denial.', false, 'english', 40, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Hungry bellies have no ears.', false, 'english', 28, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Idle folks lack no excuses.', false, 'english', 27, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Just as the twig is bent, the tree is inclined.', false, 'english', 47, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Keep a thing seven years and you will find a use for it.', false, 'english', 56, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Keep your mouth shut and your ears open.', false, 'english', 40, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Keep your mouth shut and your eyes open.', false, 'english', 40, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Those who live in glass houses should not throw stones.', false, 'english', 55, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Time and tide wait for no man.', false, 'english', 30, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Time cures all things.', false, 'english', 22, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Time is money.', false, 'english', 14, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Time is the great healer.', false, 'english', 25, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('From pillar to post.', false, 'english', 20, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Gentility without ability is worse than plain beggary.', false, 'english', 54, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Get a name to rise early, and you may lie all day.', false, 'english', 50, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Gifts from enemies are dangerous.', false, 'english', 33, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Give every man thy ear, but few thy voice.', false, 'english', 42, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Creditors have better memories than debtors.', false, 'english', 44, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Cross the stream where it is shallowest.', false, 'english', 40, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Crows do not pick crow\u2019s eyes.', false, 'english', 30, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('A bad beginning makes a bad ending.', false, 'english', 35, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('A bad corn promise is better than a good lawsuit.', false, 'english', 49, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('A bad workman quarrels with his tools.', false, 'english', 38, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('A bargain is a bargain.', false, 'english', 23, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('A beggar can never be bankrupt.', false, 'english', 31, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('A bird in the hand is worth two in the bush.', false, 'english', 44, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('A cat in gloves catches no mice.', false, 'english', 32, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('A city that parleys is half gotten.', false, 'english', 35, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('A civil denial is better than a rude grant.', false, 'english', 43, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Two is company, but three is none.', false, 'english', 34, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Velvet paws hide sharp claws.', false, 'english', 29, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Virtue is its own reward.', false, 'english', 25, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Wait for the cat to jump.', false, 'english', 25, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('All bread is not baked in one oven.', false, 'english', 35, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('All cats are grey in the dark (in the night).', false, 'english', 45, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('All covet, all lose.', false, 'english', 20, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('All doors open to courtesy.', false, 'english', 27, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('All is fish that comes to his net.', false, 'english', 34, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('All is not lost that is in peril.', false, 'english', 33, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('All is well that ends well.', false, 'english', 27, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('All lay load on the willing horse.', false, 'english', 34, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('All men can\u2019t be first.', false, 'english', 23, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('All men can\u2019t be masters.', false, 'english', 25, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('All promises are either broken or kept.', false, 'english', 39, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('All roads lead to Rome .', false, 'english', 24, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('All sugar and honey.', false, 'english', 20, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('All that glitters is not gold.', false, 'english', 30, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('All things are difficult before they are easy.', false, 'english', 46, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('All truths are not to be told.', false, 'english', 30, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('All work and no play makes Jack a dull boy.', false, 'english', 43, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('\u201cAlmost\u201d never killed a fly (was never hanged).', false, 'english', 47, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Among the blind the one-eyed man is king.', false, 'english', 41, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Walls have ears.', false, 'english', 16, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Wash your dirty linen at home.', false, 'english', 30, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Waste not, want not.', false, 'english', 20, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('We know not what is good until we have lost it.', false, 'english', 47, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('We never know the value of water till the well is dry.', false, 'english', 54, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('We shall see what we shall see.', false, 'english', 31, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('We soon believe what we desire.', false, 'english', 31, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Wealth is nothing without health.', false, 'english', 33, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Well begun is half done.', false, 'english', 24, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('What can\u2019t be cured, must be endured.', false, 'english', 37, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('What is bred in the bone will not go out of the flesh.', false, 'english', 54, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('What is done by night appears by day.', false, 'english', 37, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('What is done cannot be undone.', false, 'english', 30, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('What is got over the devil\u2019s back is spent under his belly.', false, 'english', 59, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('What is lost is lost.', false, 'english', 21, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('What is sauce for the goose is sauce for the gander.', false, 'english', 52, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('What is worth doing at alt is worth doing well.', false, 'english', 47, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('What must be, must be.', false, 'english', 22, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('What the heart thinks the tongue speaks.', false, 'english', 40, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('A clean fast is better than a dirty breakfast.', false, 'english', 46, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('A clean hand wants no washing..', false, 'english', 31, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('A clear conscience laughs at false accusations.', false, 'english', 47, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('A close mouth catches no flies.', false, 'english', 31, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('A cock is valiant on his own dunghill.', false, 'english', 38, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('A cracked bell can never sound well.', false, 'english', 36, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('A creaking door hangs long on its hinges.', false, 'english', 41, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('A cursed cow has short horns.', false, 'english', 29, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('A danger foreseen is half avoided.', false, 'english', 34, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('A drop in the bucket.', false, 'english', 21, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('A drowning man will catch at a straw.', false, 'english', 37, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('A fair face may hide a foul heart.', false, 'english', 34, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('A fault confessed is half redressed.', false, 'english', 36, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('A bird may be known by its song.', false, 'english', 32, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('A black hen lays a white egg.', false, 'english', 29, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('A blind leader of the blind.', false, 'english', 28, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('A blind man would be glad to see.', false, 'english', 33, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('A broken friendship may be soldered, but will never be sound.', false, 'english', 61, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('A burden of one\u2019s own choice is not felt.', false, 'english', 41, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('A burnt child dreads the fire.', false, 'english', 30, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('A fly in the ointment.', false, 'english', 22, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('A fool always rushes to the fore.', false, 'english', 33, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('A threatened blow is seldom given.', false, 'english', 34, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('A tree is known by its fruit.', false, 'english', 29, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('A wager is a fool\u2019s argument.', false, 'english', 29, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('A watched pot never boils.', false, 'english', 26, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('A wise man changes his mind, a fool never will.', false, 'english', 47, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('A wolf in sheep\u2019s clothing.', false, 'english', 27, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('A wonder lasts but nine days.', false, 'english', 29, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('A word is enough to the wise.', false, 'english', 29, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('A word spoken is past recalling.', false, 'english', 32, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Actions speak louder than words.', false, 'english', 32, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Adversity is a great schoolmaster.', false, 'english', 34, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Adversity makes strange bedfellows.', false, 'english', 35, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('After a storm comes a calm.', false, 'english', 27, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('After dinner comes the reckoning.', false, 'english', 33, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('After dinner sit (sleep) a while, after supper walk a mile.', false, 'english', 59, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('After rain comes fair weather.', false, 'english', 30, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('After us the deluge.', false, 'english', 20, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Agnes come on horseback, but go away on foot.', false, 'english', 45, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('All are good lasses, but whence come the bad wives?', false, 'english', 51, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('All are not friends that speak us fair.', false, 'english', 39, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('All are not hunters that blow the horn.', false, 'english', 39, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('All are not merry that dance lightly.', false, 'english', 37, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('All are not saints that go to church.', false, 'english', 37, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('All asses wag their ears.', false, 'english', 25, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('An apple a day keeps the doctor away.', false, 'english', 37, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('An hole in a lion\u2019s skin.', false, 'english', 25, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('An hole is but an hole, though laden with gold.', false, 'english', 47, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('An hole loaded with gold climbs to the top of the castle.', false, 'english', 57, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('An empty hand is no lure for a hawk.', false, 'english', 36, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('An empty sack cannot stand upright.', false, 'english', 35, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('An empty vessel gives a greater sound than a full barrel.', false, 'english', 57, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('An evil chance seldom comes alone.', false, 'english', 34, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('An honest tale speeds best, being plainly told.', false, 'english', 47, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('An hour in the morning is worth two in the evening.', false, 'english', 51, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('An idle brain is the devil\u2019s workshop.', false, 'english', 38, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('An ill wound is cured, not an ill name.', false, 'english', 39, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('An oak is not felled at one stroke.', false, 'english', 35, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('An old dog barks not in vain.', false, 'english', 29, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('An open door may tempt a saint.', false, 'english', 31, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('An ounce of discretion is worth a pound of learning.', false, 'english', 52, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('An ox is taken by the horns, and a man by the tongue.', false, 'english', 53, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('An unfortunate man would be drowned in a teacup.', false, 'english', 48, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Anger and haste hinder good counsel.', false, 'english', 36, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Any port in a storm.', false, 'english', 20, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Appearances are deceitful.', false, 'english', 26, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Appetite comes with eating.', false, 'english', 27, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('As drunk as a lord.', false, 'english', 19, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('As innocent as a babe unborn.', false, 'english', 29, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('As like as an apple to an oyster.', false, 'english', 33, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('As like as two peas.', false, 'english', 20, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('As old as the hills.', false, 'english', 20, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('As plain as the nose on a man\u2019s face.', false, 'english', 37, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('As plain as two and two make four.', false, 'english', 34, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('As snug as a bug in a rug .', false, 'english', 27, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('As sure as eggs is eggs.', false, 'english', 24, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('As the call, so the echo.', false, 'english', 25, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('As the fool thinks, so the bell clinks.', false, 'english', 39, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('As the old cock crows, so does the young.', false, 'english', 41, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('As the tree falls, so shall it lie.', false, 'english', 35, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('As the tree, so the fruit.', false, 'english', 26, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('As welcome as flowers in May.', false, 'english', 29, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('As welcome as water in one\u2019s shoes.', false, 'english', 35, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('As well be hanged for a sheep as for a lamb.', false, 'english', 44, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('As you brew, so must you drink.', false, 'english', 31, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('As you make your bed, so must you lie on it.', false, 'english', 44, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('As you sow, so shall you reap.', false, 'english', 30, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Ask no questions and you will be told no lies.', false, 'english', 46, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('At the ends of the earth.', false, 'english', 25, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Bacchus has drowned more men than Neptune .', false, 'english', 43, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Bad news has wings.', false, 'english', 19, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Barking does seldom bite.', false, 'english', 25, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Be slow to promise and quick to perform.', false, 'english', 40, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Be swift to hear, slow to speak.', false, 'english', 32, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Beauty is but skin-deep.', false, 'english', 24, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Beauty lies in lover\u2019s eyes.', false, 'english', 28, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Before one can say Jack Robinson.', false, 'english', 33, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Before you make a friend eat a bushel of salt with him.', false, 'english', 55, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Beggars cannot be choosers.', false, 'english', 27, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Believe not all that you see nor half what you hear.', false, 'english', 52, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Best defense is offense.', false, 'english', 24, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Better a glorious death than a shameful life.', false, 'english', 45, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Better a lean peace than a fat victory.', false, 'english', 39, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Better a little fire to warm us, than a great one to burn us.', false, 'english', 61, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Better an egg today than a hen tomorrow.', false, 'english', 40, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Better an open enemy than a false friend.', false, 'english', 41, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Better be alone than in bad company.', false, 'english', 36, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Better be born lucky than rich.', false, 'english', 31, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Better be envied than pitied.', false, 'english', 29, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Better be the head of a dog than the tail of a lion.', false, 'english', 52, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Better deny at once than promise long.', false, 'english', 38, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Better die standing than live kneeling.', false, 'english', 39, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Better early than late.', false, 'english', 23, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Better give a shilling than lend a half-crown.', false, 'english', 46, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Better go to bed supperless than rise in debt.', false, 'english', 46, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Better late than never.', false, 'english', 23, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Better lose a jest than a friend.', false, 'english', 33, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Better one-eyed than stone-blind.', false, 'english', 33, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Better the devil you know than the devil you don\u2019t.', false, 'english', 51, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Better the foot slip than the tongue.', false, 'english', 37, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Better to do well than to say well.', false, 'english', 35, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Better to reign in hell, than serve in heaven.', false, 'english', 46, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Better unborn than untaught.', false, 'english', 28, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Better untaught than ill-taught.', false, 'english', 32, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Between the cup and the lip a morsel may slip.', false, 'english', 46, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Between the devil and the deep (blue) sea.', false, 'english', 42, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Between two evils \u2019tis not worth choosing.', false, 'english', 42, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Between two stools one goes (falls) to the ground.', false, 'english', 50, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Between the upper and nether millstone.', false, 'english', 39, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Betwixt and between.', false, 'english', 20, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Beware of a silent dog and still water.', false, 'english', 39, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Bind the sack before it be full.', false, 'english', 32, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Birds of a feather flock together.', false, 'english', 34, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Blind men can judge no colours.', false, 'english', 31, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Blood is thicker than water.', false, 'english', 28, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Borrowed garments never fit well.', false, 'english', 33, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Brevity is the soul of wit.', false, 'english', 27, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Burn not your house to rid it of the mouse.', false, 'english', 43, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Business before pleasure.', false, 'english', 25, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('By doing nothing we learn to do ill.', false, 'english', 36, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('By hook or by crook.', false, 'english', 20, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('By the street of \u2018by-and-bye\u2019 one arrives at the house of \u2018Never\u2019.', false, 'english', 66, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Calamity is man\u2019s true touchstone.', false, 'english', 34, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Care killed the cat.', false, 'english', 20, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Catch the bear before you sell his skin.', false, 'english', 40, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Caution is the parent of safety.', false, 'english', 32, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Charity begins at home.', false, 'english', 23, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Cheapest is the dearest.', false, 'english', 24, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Cheek brings success.', false, 'english', 21, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Children and fools must not play with edged tools.', false, 'english', 50, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Children are poor men\u2019s riches.', false, 'english', 31, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Choose an author as you choose a friend.', false, 'english', 40, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Christmas comes but once a year, (but when it comes it brings good cheer).', false, 'english', 74, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Circumstances alter cases.', false, 'english', 26, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Claw me, and I will claw thee.', false, 'english', 30, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Cleanliness is next to godliness.', false, 'english', 33, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Company in distress makes trouble less.', false, 'english', 39, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Confession is the first step to repentance.', false, 'english', 43, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Counsel is no command..', false, 'english', 23, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Creditors have better memories than debtors.', false, 'english', 44, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Cross the stream where it is shallowest.', false, 'english', 40, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Crows do not pick crow\u2019s eyes.', false, 'english', 30, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Curiosity killed a cat.', false, 'english', 23, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Curses like chickens come home to roost.', false, 'english', 40, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Custom is a second nature.', false, 'english', 26, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Custom is the plague of wise men and the idol of fools.', false, 'english', 55, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Cut your coat according to your cloth.', false, 'english', 38, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Death is the grand leveler.', false, 'english', 27, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Death pays all debts.', false, 'english', 21, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Death when it comes will have no denial.', false, 'english', 40, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Debt is the worst poverty.', false, 'english', 26, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Deeds, not words.', false, 'english', 17, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Delays are dangerous.', false, 'english', 21, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Desperate diseases must have desperate remedies.', false, 'english', 48, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Diligence is the mother of success (good luck).', false, 'english', 47, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Diseases are the interests of pleasures.', false, 'english', 40, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Divide and rule.', false, 'english', 16, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Do as you would be done by.', false, 'english', 27, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Dog does not eat dog.', false, 'english', 21, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Dog eats dog.', false, 'english', 13, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Dogs that put up many hares kill none.', false, 'english', 38, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Doing is better than saying.', false, 'english', 28, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Don\u2019t count your chickens before they are hatched.', false, 'english', 50, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Don\u2019t cross the bridges before you come to them.', false, 'english', 48, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Don\u2019t have thy cloak to make when it begins to rain.', false, 'english', 52, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Don\u2019t keep a dog and bark yourself.', false, 'english', 35, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Don\u2019t look a gift horse in the mouth.', false, 'english', 37, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Don\u2019t put all your eggs in one basket.', false, 'english', 38, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Don\u2019t sell the bear\u2019s skin before you\u2019ve caught it.', false, 'english', 51, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Don\u2019t trouble trouble until trouble troubles you.', false, 'english', 49, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Don\u2019t whistle (halloo) until you are out of the wood.', false, 'english', 53, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Dot your i\u2019s and cross your t\u2019s.', false, 'english', 32, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Draw not your bow till your arrow is fixed.', false, 'english', 43, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Drive the nail that will go.', false, 'english', 28, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Drunken days have all their tomorrow.', false, 'english', 37, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Drunkenness reveals what soberness conceals.', false, 'english', 44, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Dumb dogs are dangerous.', false, 'english', 24, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Each bird loves to hear himself sing.', false, 'english', 37, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Early to bed and early to rise makes a man healthy, wealthy and wise.', false, 'english', 69, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Easier said than done.', false, 'english', 22, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('East or West ? home is best.', false, 'english', 28, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Easy come, easy go.', false, 'english', 19, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Eat at pleasure, drink with measure.', false, 'english', 36, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Empty vessels make the greatest (the most) sound.', false, 'english', 49, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Enough is as good as a feast.', false, 'english', 29, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Envy shoots at others and wounds herself.', false, 'english', 41, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Even reckoning makes long friends.', false, 'english', 34, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Every hole loves to hear himself bray.', false, 'english', 38, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Every barber knows that.', false, 'english', 24, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Every bean has its black.', false, 'english', 25, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Every bird likes its own nest.', false, 'english', 30, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Every bullet has its billet.', false, 'english', 28, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Every country has its customs.', false, 'english', 30, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Every dark cloud has a silver lining.', false, 'english', 37, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Every day is not Sunday.', false, 'english', 24, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Every dog has his day.', false, 'english', 22, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Every dog is a lion at home.', false, 'english', 28, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Every dog is valiant at his own door.', false, 'english', 37, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Every Jack has his Jill.', false, 'english', 24, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Every man has a fool in his sleeve.', false, 'english', 35, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Every man has his faults.', false, 'english', 25, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Every man has his hobby-horse.', false, 'english', 30, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Every man is the architect of his own fortunes.', false, 'english', 47, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Every man to his taste.', false, 'english', 23, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Every miller draws water to his own mill.', false, 'english', 41, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Every mother thinks her own gosling a swan.', false, 'english', 43, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Every one\u2019s faults are not written in their foreheads.', false, 'english', 54, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Every tub must stand on its own bottom..', false, 'english', 40, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Every white has its black, and every sweet its sour.', false, 'english', 52, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Every why has a wherefore.', false, 'english', 26, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Everybody\u2019s business is nobody\u2019s business.', false, 'english', 42, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Everything comes to him who waits.', false, 'english', 34, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Everything is good in its season.', false, 'english', 33, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Evil communications corrupt good manners.', false, 'english', 41, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Experience is the mother of wisdom.', false, 'english', 35, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Experience keeps a dear school, but fools learn in no other.', false, 'english', 60, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Experience keeps no school, she teaches her pupils singly.', false, 'english', 58, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Extremes meet.', false, 'english', 14, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Facts are stubborn things..', false, 'english', 27, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Faint heart never won fair lady.', false, 'english', 32, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Fair without, foul (false) within.', false, 'english', 34, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Fair words break no bones.', false, 'english', 26, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('False friends are worse than open enemies.', false, 'english', 42, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Familiarity breeds contempt.', false, 'english', 28, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Far from eye, far from heart.', false, 'english', 29, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Fasting comes after feasting.', false, 'english', 29, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Faults are thick where love is thin.', false, 'english', 36, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Feast today and fast tomorrow.', false, 'english', 30, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Fine feathers make fine birds.', false, 'english', 30, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Fine words butter no parsnips.', false, 'english', 30, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('First catch your hare.', false, 'english', 22, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('First come, first served.', false, 'english', 25, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('First deserve and then desire.', false, 'english', 30, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('First think, then speak.', false, 'english', 24, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Fish and company stink in three days.', false, 'english', 37, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Fish begins to stink at the head.', false, 'english', 33, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Follow the river and you\u2019ll get to the sea.', false, 'english', 43, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Fool\u2019s haste is no speed.', false, 'english', 25, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Fools and madmen speak the truth.', false, 'english', 33, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Fools grow without watering.', false, 'english', 28, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Fools may sometimes speak to the purpose.', false, 'english', 41, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Fools never know when they are well.', false, 'english', 36, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Fools rush in where angels fear to tread.', false, 'english', 41, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('For the love of the game.', false, 'english', 25, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Forbearance is no acquittance.', false, 'english', 30, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Forbidden fruit is sweet.', false, 'english', 25, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Forewarned is forearmed.', false, 'english', 24, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Fortune favors the brave (the bold).', false, 'english', 36, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Fortune is easily found, but hard to be kept.', false, 'english', 45, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Four eyes see more (better) than two.', false, 'english', 37, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Friends are thieves of time.', false, 'english', 28, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('From bad to worse.', false, 'english', 18, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('From pillar to post.', false, 'english', 20, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Gentility without ability is worse than plain beggary.', false, 'english', 54, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Get a name to rise early, and you may lie all day.', false, 'english', 50, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Gifts from enemies are dangerous.', false, 'english', 33, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Give a fool rope enough, and he will hang himself.', false, 'english', 50, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Give every man thy ear, but few thy voice.', false, 'english', 42, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Give him an inch and he\u2019ll take an ell.', false, 'english', 39, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Give never the wolf the weather to keep.', false, 'english', 40, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Gluttony kills more men than the sword.', false, 'english', 39, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Go to bed with the lamb and rise with the lark.', false, 'english', 47, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Good clothes open all doors.', false, 'english', 28, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Good counsel does no harm.', false, 'english', 26, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Good health is above wealth.', false, 'english', 28, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Good masters make good servants.', false, 'english', 32, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Good words and no deeds.', false, 'english', 24, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Good words without deeds are rushes and reeds.', false, 'english', 46, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Gossiping and lying go hand in hand.', false, 'english', 36, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Grasp all, lose all.', false, 'english', 20, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Great barkers are no biters.', false, 'english', 28, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Great boast, small roast.', false, 'english', 25, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Great cry and little wool.', false, 'english', 26, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Great spenders are bad lenders.', false, 'english', 31, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Great talkers are great liars.', false, 'english', 30, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Great talkers are little doers.', false, 'english', 31, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Greedy folk have long arms.', false, 'english', 27, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Habit cures habit.', false, 'english', 18, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Half a loaf is better than no bread.', false, 'english', 36, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('\u201cHamlet\u201d without the Prince of Denmark .', false, 'english', 40, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Handsome is that handsome does.', false, 'english', 31, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Happiness takes no account of time.', false, 'english', 35, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Happy is he that is happy in his children.', false, 'english', 42, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Hard words break no bones.', false, 'english', 26, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Hares may pull dead lions by the beard.', false, 'english', 39, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Harm watch, harm catch.', false, 'english', 23, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Haste makes waste.', false, 'english', 18, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Hasty climbers have sudden falls.', false, 'english', 33, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Hate not at the first harm.', false, 'english', 27, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Hatred is blind, as well as love.', false, 'english', 33, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Hawks will not pick hawks\u2019 eyes.', false, 'english', 32, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He begins to die that quits his desires.', false, 'english', 40, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He cannot speak well that cannot hold his tongue.', false, 'english', 49, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He carries fire in one hand and water in the other.', false, 'english', 51, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He dances well to whom fortune pipes.', false, 'english', 37, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He gives twice who gives in a trice.', false, 'english', 36, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He goes long barefoot that waits for dead man\u2019s shoes.', false, 'english', 54, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He is a fool that forgets himself.', false, 'english', 34, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He is a good friend that speaks well of us behind our backs.', false, 'english', 60, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He is happy that thinks himself so.', false, 'english', 35, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He is lifeless that is faultless.', false, 'english', 33, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He is not fit to command others that cannot command himself.', false, 'english', 60, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He is not laughed at that laughs at himself first.', false, 'english', 50, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He is not poor that has little, but he that desires much.', false, 'english', 57, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He jests at scars that never felt a wound.', false, 'english', 42, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He knows best what good is that has endured evil.', false, 'english', 49, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He knows how many beans make five.', false, 'english', 34, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He knows much who knows how to hold his tongue.', false, 'english', 47, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He laughs best who laughs last.', false, 'english', 31, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He lives long that lives well.', false, 'english', 30, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He must needs swim that is held up by the chin.', false, 'english', 47, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He should have a long spoon that sups with the devil.', false, 'english', 53, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He smells best that smells of nothing.', false, 'english', 38, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He that comes first to the hill may sit where he will.', false, 'english', 54, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He that commits a fault thinks everyone speaks of it.', false, 'english', 53, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He that does you an i!i turn will never forgive you.', false, 'english', 52, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He that fears every bush must never go a-birding.', false, 'english', 49, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He that fears you present wiil hate you absent.', false, 'english', 47, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He that goes a borrowing, goes a sorrowing.', false, 'english', 43, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He that goes barefoot must not plant thorns.', false, 'english', 44, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He that has a full purse never wanted a friend.', false, 'english', 47, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He that has a great nose thinks everybody is speaking of it.', false, 'english', 60, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He that has an ill name is half hanged.', false, 'english', 39, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He that has no children knows not what love is.', false, 'english', 47, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He that has He head needs no hat.', false, 'english', 33, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He that has no money needs no purse.', false, 'english', 36, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He that is born to be hanged shall never be drowned.', false, 'english', 52, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He that is full of himself is very empty.', false, 'english', 41, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He that is ill to himself will be good to nobody.', false, 'english', 49, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He that is warm thinks all so.', false, 'english', 30, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He that knows nothing doubts nothing.', false, 'english', 37, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He that lies down with dogs must rise up with fleas.', false, 'english', 52, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He that lives with cripples learns to limp.', false, 'english', 43, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He that mischief hatches, mischief catches.', false, 'english', 43, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He that never climbed never fell.', false, 'english', 33, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He that once deceives is ever suspected.', false, 'english', 40, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He that promises too much means nothing.', false, 'english', 40, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He that respects not is not respected.', false, 'english', 38, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He that seeks trouble never misses.', false, 'english', 35, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He that serves everybody is paid by nobody.', false, 'english', 43, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He that serves God for money will serve the devil for better wages.', false, 'english', 67, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He that spares the bad injures the good.', false, 'english', 40, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He that talks much errs much.', false, 'english', 29, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He that talks much lies much.', false, 'english', 29, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He that will eat the kernel must crack the nut.', false, 'english', 47, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He that will not when he may, when he will he shall have nay.', false, 'english', 61, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He that will steal an egg will steal an ox.', false, 'english', 43, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He that will thrive, must rise at five.', false, 'english', 39, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He that would eat the fruit must climb the tree.', false, 'english', 48, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He that would have eggs must endure the cackling of hens.', false, 'english', 57, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He who is born a fool is never cured.', false, 'english', 37, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He who hesitates is lost.', false, 'english', 25, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He who likes borrowing dislikes paying.', false, 'english', 39, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He who makes no mistakes, makes nothing.', false, 'english', 40, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He who pleased everybody died before he was born.', false, 'english', 49, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He who says what he likes, shall hear what he doesn\u2019t like.', false, 'english', 59, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He who would catch fish must not mind getting wet.', false, 'english', 50, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He who would eat the nut must first crack the shell.', false, 'english', 52, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He who would search for pearls must dive below.', false, 'english', 47, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He will never set the Thames on fire.', false, 'english', 37, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('He works best who knows his trade.', false, 'english', 34, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Head cook and bottle-washer.', false, 'english', 28, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Health is not valued till sickness comes.', false, 'english', 41, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('His money burns a hole in his pocket.', false, 'english', 37, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Honesty is the best policy.', false, 'english', 27, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Honey is not for the hole\u2019s mouth.', false, 'english', 34, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Honey is sweet, but the bee stings.', false, 'english', 35, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Honour and profit lie not in one sack.', false, 'english', 38, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Honours change manners..', false, 'english', 24, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Hope is a good breakfast, but a bad supper.', false, 'english', 43, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Hope is the poor man\u2019s bread.', false, 'english', 29, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Hunger breaks stone walls.', false, 'english', 26, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Hunger finds no fault with cookery.', false, 'english', 35, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Hunger is the best sauce.', false, 'english', 25, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Hungry bellies have no ears.', false, 'english', 28, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Idle folks lack no excuses.', false, 'english', 27, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Idleness is the mother of all evil.', false, 'english', 35, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Idleness rusts the mind.', false, 'english', 24, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('If an hole (donkey) bray at you, don\u2019t bray at him.', false, 'english', 51, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('If ifs and ans were pots and pans\u2026', false, 'english', 34, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('If my aunt had been a man, she\u2019d have been my uncle.', false, 'english', 52, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('If the blind lead the blind, both shall fall into the ditch..', false, 'english', 61, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('If the sky falls, we shall catch larks.', false, 'english', 39, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('If there were no clouds, we should not enjoy the sun.', false, 'english', 53, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('If things were to be done twice all would be wise.', false, 'english', 50, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('If we can\u2019t as we would, we must do as we can.', false, 'english', 46, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('If wishes were horses, beggars might ride.', false, 'english', 42, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('If you agree to carry the calf, they\u2019ll make you carry the cow.', false, 'english', 63, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('If you cannot bite, never show your teeth.', false, 'english', 42, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('If you cannot have the best, make the best of what you have.', false, 'english', 60, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('If you dance you must pay the fiddler.', false, 'english', 38, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('If you laugh before breakfast you\u2019ll cry before supper.', false, 'english', 55, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('If you run after two hares, you will catch neither.', false, 'english', 51, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('If you sell the cow, you sell her milk too.', false, 'english', 43, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('If you throw mud enough, some of it will stick.', false, 'english', 47, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('If you try to please all you will please none.', false, 'english', 46, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('If you want a thing well done, do it yourself.', false, 'english', 46, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Ill-gotten gains never prosper.', false, 'english', 31, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('Ill-gotten, ill-spent.', false, 'english', 22, 0);
INSERT INTO TYPING (CONTENT, CONTENT_TYPE, LANGUAGE, LENGTH, VIEW_COUNT) VALUES ('In every beginning think of the end.', false, 'english', 36, 0);
