

name: Backend-Deploy-Local

on:
  push:
    branches: 
      - main
    paths :
      - "backend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: make application-secret.yml
        run: |
          cd ./dockerfile/backend/
          touch ./application-secret.yml
          echo "${{ secrets.LOCAL_SECRET_YML }}" > ./application-secret.yml
        shell: bash
      -
        name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: baikjonghyun/tamago
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfile/backend/
          file: ./dockerfile/backend/Dockerfile-Local
          platforms: linux/amd64
          push: true
          tags: baikjonghyun/tamago-local:lastest