# This is a basic workflow to help you get started with Actions

name: Backend-Deploy

on:
  push:
    branches: 
      - main
    paths :
      - "backend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: make application-secret.yml
        run: |
          cd ./dockerfile/backend/
          touch ./application-secret.yml
          echo "${{ secrets.SECRET_YML }}" > ./application-secret.yml
        shell: bash
      -
        name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: baikjonghyun/tamago
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfile/backend/
          file: ./dockerfile/backend/Dockerfile
          platforms: linux/amd64
          push: true
          tags: baikjonghyun/tamago:lastest
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_SSH_ID }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
<<<<<<< HEAD
=======
            whoami
            cd /home
            sudo chown -R ubuntu:ubuntu ubuntu
            cd /home/ubuntu/dockerfile/backend
             echo -e "\
             +------------------------------------+
             |              1. build              |
             +------------------------------------+"
            
            echo ">>>>>> making secret yml..."
            echo "${{ secrets.EC2_SECRET_YML }}" > application-secret.yml
>>>>>>> 71dbb54cea6118bd9b64e83cc1d02904ac16ccc9
            echo -e "\
             +------------------------------------+
             |                run                 |
             +------------------------------------+"
            cd /home/ubuntu/dockerfile/backend
            chmod +x backend_install.sh || exit 1
            chmod +x delete_not_use_image_file.sh || exit 1
            sudo ./backend_install.sh || exit 1
            sudo ./delete_not_use_image_file.sh || exit 1