name: "Chromatic Deployment"

on:
  push:
    branches:
      - main
    paths:
      - "client/**"

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          cd ./client
          yarn

      - name: Build storybook
        run: |
          cd ./client
          yarn build-storybook

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          workingDir: client
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
