name: "Chromatic Deployment"

on:
  push:
    branches:
      - main
    paths:
      - "client/**"

# List of jobs
jobs:
  test:
    # Operating System
    runs-on: ubuntu-latest
    # list of steps of actions
    steps:
      - name: Check repository
      - uses: actions/checkout@v1
        run: cd ./client
      - name: Install dependencies
        run: yarn
        #👇 Adds Chromatic as a step in the workflow
      - name: Publish to Chromatic
      - uses: chromaui/action@v1
        # Chromatic's GitHub Action options
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          workingDir: client
