name: Frontend-Build-Test

on:
  pull_request:
    branches:
      - "main"
      - "feature/**"
      - "fix/**"
      - "refactor/**"
    paths:
      - "client/**"

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Cache Dependencies
        id: cache-yarn
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
            ${{ runner.os }}-
      - if: ${{ steps.cache-yarn.outputs.cache-hit == 'true' }}
        run: echo "node modules cache hit!"

      - name: Install Dependencies
        if: ${{ steps.cache-yarn.outputs.cache-hit != 'true' }}
        run: |
          cd ./client
          yarn

      - name: Test with jest
        run: |
          cd ./client
          yarn test

      - name: Build with yarn
        run: |
          cd ./client
          yarn install --frozen-lockfile
          yarn build
